# Generated by Django 4.0.3 on 2022-03-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.CharField(default=None, max_length=100)),
                ('category_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=250)),
                ('equipment_serial_number', models.CharField(max_length=100)),
                ('equipment_code', models.IntegerField(default=0)),
                ('equipment_model', models.CharField(default=None, max_length=100)),
                ('equipment_type', models.CharField(default=None, max_length=100)),
                ('equipment_cost', models.FloatField(default=None)),
                ('available', models.BooleanField(default=True)),
                ('notes', models.CharField(default=None, max_length=500)),
                ('damaged', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(default=None, max_length=500)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='inventory.equipment')),
                ('supply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fname', models.CharField(max_length=50)),
                ('employee_lname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('date_returned', models.DateTimeField(default=None)),
                ('notes', models.CharField(default=None, max_length=500)),
                ('employee_allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='inventory.employee')),
                ('equipment_allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='inventory.equipment')),
            ],
        ),
    ]
