# Generated by Django 4.0.3 on 2022-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
