# Generated by Django 4.0.3 on 2022-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_cost',
            field=models.FloatField(default=None, null=True),
        ),
    ]
