# Generated by Django 4.0.3 on 2022-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipment_equipment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
