# Generated by Django 4.0.3 on 2022-03-22 18:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_equipment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
