# Generated by Django 4.0.3 on 2022-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_supplyconsumption_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_returned',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
